---
kind: pipeline
type: kubernetes
name: linux

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/drone/drone-go

steps:
  - name: build:
    image: golang:1.6
    commands:
      - go test -v github.com/drone/drone-go/drone
